### ISSUE TITLE
Create Twelve Character Thumbnails

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#10]
Create 12 Thumbnails of characters to then model them in 3d.
Implement them in game.

- [x] Main Character Thumbnails

- [x] Bosses Thumbnails

- [x] Enemies Thumbnails

**EXPECTED RESULT:**

12 different pngs that give us a little idea about characters that you have to create and implement in game.

[Concept Art Folder](https://github.com/Kenjor97/KriticGamesProject/tree/master/ConceptArt)

**Comment by Kenjor97** [comment]
Closed issue in this commit
https://github.com/Kenjor97/KriticGamesProject/commit/656d19b8f61118b106e659db3f2022a9107f80e9
