### ISSUE TITLE
Create Twelve Props Thumbnails

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#11]
12 thumbnails of props/buildings/level elements.

**Comment by Kenjor97** [comment]
Create 12 Thumbnails of props to then model them in 3d.
Implement them in game.

- [x] Box Thumbnail

- [x] Chest Thumbnail

- [x] Door Thumbnail

- [x] Skewertrap Thumbnail

- [x]  Boots Thumbnail

- [x] Cheatingblade Thumbnail

- [x] Collectible Thumbnail

- [x] Keys Thumbnail

- [x] Padlock Thumbnail

- [x] Pressbutton Thumbnail

- [x] Stairs Thumbnail

- [x] Lever Thumbnail

**EXPECTED RESULT:**

*12 different pngs that give us a little idea about props that you have to create and implement in the project.*

[Concept Art Folder](https://github.com/Kenjor97/KriticGamesProject/tree/master/ConceptArt)

**Comment by Kenjor97** [comment]
Closed issue in this commit
https://github.com/Kenjor97/KriticGamesProject/commit/242eb23ae4f93fffcf14db415f851751b4e43291
