### ISSUE TITLE
Create Characters Size Chart

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#12]
Comparative image for player, characters and enemies sizes. 
Thumbnails can be used.

- [x] Level Characters Size Chart Complete (Kenjor97)

**EXPECTED RESULT:**

*Generate a comparative image for level characters sizes (Thumbnails can be used)*

[Concept Art Folder](https://github.com/Kenjor97/KriticGamesProject/tree/master/ConceptArt)

**Comment by Kenjor97** [comment]
Closed issue in this commits

https://github.com/Kenjor97/KriticGamesProject/commit/63da4a1c7860c96bce695dad527363e47073e3fc
