### ISSUE TITLE
Create Level Props Size Chart

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#13]
Comparative image for level elements sizes. 
Thumbnails can be used.

- [x] Level Props Size Chart Complete (Kenjor97)

**EXPECTED RESULT:**

*Generate a comparative image for level elements sizes (Thumbnails can be used)*

[Concept Art Folder](https://github.com/Kenjor97/KriticGamesProject/tree/master/ConceptArt)

**Comment by Kenjor97** [comment]
Closed issue in this commits

https://github.com/Kenjor97/KriticGamesProject/commit/63da4a1c7860c96bce695dad527363e47073e3fc
