### ISSUE TITLE
Create 8 Props And Implement In Level

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#14]
Create from the concept arts and thumbnails in 3d the proposed props and then implement them in unity.

8 final props implemented in level.
- [x] 4 props - Kenneth
- [x] 4 props - Adrián

**EXPECTED RESULT:**

*Model 8 props from the proposed thumbnails and implement these props in the project.*

[Art Sources Folder](https://github.com/Kenjor97/KriticGamesProject/tree/master/ArtSources)

**Comment by Kenjor97** [comment]
Finish.

**Comment by Kenjor97** [comment]
Closed issue in this commit
https://github.com/Kenjor97/KriticGamesProject/commit/59530f78443c1ccb1b39337e7d5373811db5010c
