### ISSUE TITLE
Create Game Title Screen

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#15]
Create all the art for the Title Screen, with an image for the Title, some props (anvil, chains, wood table)
- [x] Art Title - Adrián
- [x] Implemented - Diego

**EXPECTED RESULT:**

_Some 3D models(anvil, chains, wood table) in obj format, in the folder Meshes of the Unity Project, and some buttons with its logic in a UInity Scene, called Title. In that scenes will be the title of the game too._

**Comment by souk07** [comment]
Issue completed
