### ISSUE TITLE
Level Design Map and Level Flow Map

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#16]
- [x] Level design map detailed with all gameplay elements.
- [x] Differents actions that the player must do to complete the level.

**EXPECTED RESULT:**

_2 png images in the folder WikiResources, with the level design map and the level flow map._

**Comment by souk07** [comment]
Issue close in this commit https://github.com/Kenjor97/KriticGamesProject/commit/948c8e9679fffc7d3c501d05fd35dc654db3dd98
