### ISSUE TITLE
Create and Impement Logo Screen Art in the Unity Project

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#18]
Create a Logo of the team in photoshop and implement it in a Unity scene with an animation(fading, movement...) in order to have  a properly Logo screen, with transitions and in the right place in the order of the screens.
- [x] Create Logo - souk07
- [x] Implement the Logo with an animation in Unity, in the Logo Screen - DiegoDCV

 **EXPECTED RESULT:**

_We expect to have a .png image archive with the Kritic Games' Logo, put it in the Art Sources folder , create a Unity scene with it and a properly animation._

**Comment by DiegoDCV** [comment]
Closed issue in this commit https://github.com/Kenjor97/KriticGamesProject/commit/35908f92877ab5dc3225d473947b21e37b0efd04
