### ISSUE TITLE
Add Background And Logo To Concept Art

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#19]
Add a background and logo to all the Concept Art

**Comment by Kenjor97** [comment]
Create a background, final title and logo to implement all the Concepts art,
for example all Prop and Character Thumbnail.

- [x] Prop Thumbnails With Backgroun And Logo

- [x] Character Thumbnails With Backgroun And Logo

**EXPECTED RESULT:**

*Get a background with final title and logo for all the art of the game.*

[Concept Art Folder](https://github.com/Kenjor97/KriticGamesProject/tree/master/ConceptArt)

**Comment by Kenjor97** [comment]
Closed issue in this commits

https://github.com/Kenjor97/KriticGamesProject/commit/08cafa4c953cf6c189313283e46af92e2ba00371

https://github.com/Kenjor97/KriticGamesProject/commit/07205713c1fe70f5fccdac01c70eddde935976bd
