### ISSUE TITLE
Implement Game Title Screen Animation

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#20]
Do an animation for the title and implement it in Unity, in a scene. The animation will be a movement of the title. At the beggining, it is in the midscreen. The animation will be a movement to the top of the screen.

**EXPECTED RESULT:**

_A Unity scene with a title screen, with the Title of the game and its animation._

**Comment by DiegoDCV** [comment]
Closed issue in the commit https://github.com/Kenjor97/KriticGamesProject/commit/35908f92877ab5dc3225d473947b21e37b0efd04
