### ISSUE TITLE
Create Game Basic Menu

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#21]
Create a basic Game Menu, that contains a Game, Settings and Exit buttons that work properly. The Game button sends you to the gameplay screen, the Settings button sends you to the Settings screen, and the exit sends you to the Desktop.

**EXPECTED RESULT:**

_A Unity Scene with a Game Menu, with at least 3 buttons, New Game, Settings and Exit. The buttons have to work correctly._

**Comment by DiegoDCV** [comment]
Closed issue in this commit https://github.com/Kenjor97/KriticGamesProject/commit/35908f92877ab5dc3225d473947b21e37b0efd04
