### ISSUE TITLE
Create Game Settings Screen and Interface in Unity

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#22]
Create the Interface of the Game Settings Screen in Photoshop and Maya; and put it in Unity with all the logic, the transitions between scenes, buttons and all the functions, with the wikis' order. 

The Settings are divided in 3 more screens, Graphics, Sound and Language.
The settings of Graphics are:
- [x] Resolution: ​1280x720​ ​(default)​ ​-​ ​1600x1200​ ​-​ ​1920x1080
- [x] Quality: ​FAST​ ​-​ ​GOOD​ ​-​ ​FANTASTIC​ ​-​ ​ULTRA
- [x] Brightness
- [x] For Colorblind

The Settings of Sound are: 
- [x] Master
- [x] Music
- [x] Effects

The Settings of Language are:

- [x] English
- [x] Spanish

**EXPECTED RESULT:**

_A UI in Unity with all the menus and elements._

**Comment by DiegoDCV** [comment]
Closed issue in this commit https://github.com/Kenjor97/KriticGamesProject/commit/c45f6639b9f699bcaa3f8a128a6fd0e49db48fa4
