### ISSUE TITLE
Implement 5 Particles System

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#23]
Create 5 particles system in photoshop and unity for implement in our game.

**EXPECTED RESULT**
_- Create 3 spritesheet .png in Photoshop for the gameplay screen_
- [x] _Walk_
- [x] _Run_
- [x] _Jump_

_- Create 2 system particles in Unity for use in main title screen_
- [x] _Fire_
- [x] _Sparks_
- [x] _Smoke_

**Comment by souk07** [comment]
Issue completed
