### ISSUE TITLE
Implement Victory/Defeat Conditions

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#27]
Implement victory and defeat conditions  in the gameplay screen, that sends to you to the Win or Lose Unity scene. The player wins when it kills the boss. The player lose when it has no lives.

**EXPECTED RESULT:**

_2 Unity scenes, with a message of you win or you lose and a script with the logic of the victory and defeat conditions_

**Comment by DiegoDCV** [comment]
Closed issue in this commit https://github.com/Kenjor97/KriticGamesProject/commit/fe4658c3f7572979423ccf8677f71858f37f2faf
