### ISSUE TITLE
Create Level With Boxes

### ISSUE THREAD

**Issue by Jason450** [Kenjor97/KriticGamesProject#32]
Create boxes for ground, hazards, ladders, props, etc and add the component "BoxCollider2D", then save them as prefabs. Create the 1st level with the prefabs.

***IMPORTANT NOTES:*** 
- Ladder's width must be 1.5 or the player won't fit.

**EXPECTED RESULT:**

*Prototype for the 1st level made with prefabs.*

**Comment by DiegoDCV** [comment]
Closed issue in this commit https://github.com/Kenjor97/KriticGamesProject/commit/807e42a97a74af8c596a6090a1cbf6f029ebf61b
